task_scheduler:
  restart: unless-stopped
  image: task_scheduler_image
  volumes:
    - /var/log/supervisor/:/var/log/supervisor/
    - /var/www/task_scheduler:/var/www/task_scheduler/
    - /root/ops_scripts:/root/ops_scripts
    - /sys/fs/cgroup:/sys/fs/cgroup
  ports:
    - "8020:80"
  environment:
